on:
# Only trigger this workflow if:
# - It's a push request
# - The branch is development
# - Files within certain paths are changed
  push:
    branches:
      - development

jobs:
  push_to_registry_amd64:
    name: Build and push amd64 image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2        
        with:
          context: ./databackup 
          file: ./docker/databackup/Dockerfile
          tags: timetobuild:databackup:dev-amd64-${{ github.run_number }}
          push: true
          
  push_to_registry_arm64v8:
    name: Build and push arm64v8 image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: ./databackup 
          file: ./docker/databackup/Dockerfile
          tags: timetobuild/databackup:dev-arm64v8-${{ github.run_number }}
      - run: docker push timetobuild/databackup:dev-arm64v8-${{ github.run_number }}

      - name: Create local changes
        run: |
          git pull
          sudo snap install yq
          yq eval ".databackup.version=${{ github.run_number }}" --inplace ./kubernetes/values.yaml
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto bump" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
      
